version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:14.11
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
     context: ../frontend
     dockerfile: Dockerfile
    volumes:
      - static_frontend:/app/result_build/

  nginx:
    image: nginx:1.22.1
    ports:
      # Live server
      - "8090:80"
      # Loc Docker dev
      # - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static_django/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_frontend:/static_frontend/
      # - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
