version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:14.11
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: .env
    # Именнованные тома для статики и медиа в контейнера django.
    # Т.е. тут будет лежать статика и меди
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    # Для простоты отладки, т.к. в этом образе мы код не меняем. Указываем
    # образ. Для тестов и отладки можете взять мой, он публичный.
    # Для сдачи диплома соберите свой собственные.
    image: virgo22/food_frontend:v1
    # Сборка из файлов, которые у вас на компе, путь относительно файла
    # docker-compose.yaml (т.е. этого)
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      # Именнованый том. Место в контейнере
      # куда будет помещена собранная статика фронта.
      - static_frontend:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"  # для запуска на сервере (внешний:внутренний)
      # Для локального запуска localhost/admin, localhosta.
#      - "80:80"
    volumes:
      # Конфиг nginx, будет лежать в той же директории,
      # что и docker-compose.yaml чтобы мы сделали его доступным в контейнере.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Именнованные тома, которые будут доступны в backend
      # Директории в контейнере nginx, где будут лежать файлы backend.
      - static:/static_django/
      - media:/media/
      # Redoc. Файлы redoc помещаем в контейнер, по указанному пути.
      - ../docs/:/usr/share/nginx/html/api/docs/
      # Место в контейнере куда попадет статика фронта.
      - static_frontend:/static_frontend/
#      - ../frontend/build:/usr/share/nginx/html/

    depends_on:
      - backend
