# Generated by Django 5.0.1 on 2024-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter an occasion to eat: breakfast, lunch or dinner",
                        max_length=200,
                        unique=True,
                        verbose_name="occasion name",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Enter a unique HEX value",
                        max_length=7,
                        unique=True,
                        verbose_name="colour",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Enter a unique slug",
                        max_length=200,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "mealtime",
                "verbose_name_plural": "mealtimes",
            },
        ),
    ]
