# Generated by Django 5.0.1 on 2024-02-05 06:52

import django_extensions.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter an occasion to eat: breakfast, lunch or dinner",
                        max_length=200,
                        unique=True,
                        verbose_name="occasion name",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Enter a unique HEX value without the #",
                        max_length=7,
                        null=True,
                        unique=True,
                        validators=[
                            django_extensions.validators.HexValidator(max_length=6)
                        ],
                        verbose_name="colour",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a unique slug",
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "mealtime",
                "verbose_name_plural": "mealtimes",
                "ordering": ("name",),
            },
        ),
    ]
