# Generated by Django 5.0.2 on 2024-02-17 09:30

import django.core.validators
import django.db.models.deletion
import recipes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a unique ingredient name",
                        max_length=200,
                        verbose_name="ingredient name",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="In grams, pieces, to taste, etc",
                        max_length=200,
                        verbose_name="measurement unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient",
                "verbose_name_plural": "ingredients",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a name for your recipe",
                        max_length=200,
                        verbose_name="recipe name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        help_text="Upload a <=3MB image for your recipe",
                        upload_to="recipes/",
                        verbose_name="recipe image",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Describe how to cook",
                        verbose_name="recipe description",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveSmallIntegerField(
                        help_text="Enter now many minutes it needs to cook",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(525960),
                        ],
                        verbose_name="cooking time",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Enter a quantity of this to use in cooking",
                        verbose_name="quantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe ingredient",
                "verbose_name_plural": "recipe ingredients",
                "ordering": ("amount",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter an occasion to eat on, e.g. breakfast, etc.",
                        max_length=200,
                        unique=True,
                        verbose_name="occasion name",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Enter a unique HEX value with the #",
                        max_length=7,
                        null=True,
                        unique=True,
                        validators=[recipes.validators.validate_hex_color],
                        verbose_name="colour",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a unique slug",
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "mealtime",
                "verbose_name_plural": "mealtimes",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="custom user",
                    ),
                ),
            ],
            options={
                "verbose_name": "favourite",
                "verbose_name_plural": "favourites",
                "ordering": ("user",),
            },
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"),
                name="unique_ingredient_measurement_unit",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="recipes.recipe",
                verbose_name="recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredient",
                verbose_name="ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
                verbose_name="recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
                verbose_name="ingredients",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="recipes.tag", verbose_name="mealtimes"),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_favorite_user_recipe"
            ),
        ),
    ]
