# Generated by Django 5.0.2 on 2024-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Enter now many minutes it needs to cook",
                verbose_name="cooking time",
            ),
            preserve_default=False,
        ),
    ]
