# Generated by Django 5.0.2 on 2024-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default=None, upload_to="recipes/images/"),
        ),
    ]
