# Generated by Django 5.0.1 on 2024-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="...")),
                (
                    "measurement_unit",
                    models.CharField(max_length=100, verbose_name="..."),
                ),
            ],
        ),
    ]
