# Generated by Django 5.0.2 on 2024-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "default_related_name": "recipe_ingredient",
                "ordering": ("amount",),
                "verbose_name": "recipe ingredient",
                "verbose_name_plural": "recipe ingredients",
            },
        ),
    ]
