# Generated by Django 5.0.2 on 2024-02-19 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipeingredient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="publication date",
            ),
            preserve_default=False,
        ),
    ]
