# Generated by Django 5.0.2 on 2024-02-14 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                help_text="Enter now many minutes it needs to cook",
                validators=[
                    django.core.validators.MaxValueValidator(525960),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="cooking time",
            ),
        ),
    ]
