# Generated by Django 5.0.2 on 2024-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipe_options_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="publised on"),
        ),
    ]
