# Generated by Django 5.0.1 on 2024-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Enter an ingredient name",
                max_length=200,
                verbose_name="ingredient name",
            ),
        ),
    ]
