# Generated by Django 5.0.1 on 2024-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Enter a unique ingredient name",
                max_length=200,
                unique=True,
                verbose_name="ingredient name",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"),
                name="Unique ingredient-measure constraint",
            ),
        ),
    ]
