# Generated by Django 5.0.2 on 2024-02-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="HeRe",
                to="recipes.ingredient",
                verbose_name="ingredient",
            ),
        ),
    ]
