# Generated by Django 5.0.2 on 2024-02-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_remove_recipe_tags_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "mealtime", "verbose_name_plural": "mealtimes"},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="recipes.tag",
                verbose_name="mealtimes",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Enter an occasion to eat on, e.g. breakfast, etc.",
                max_length=200,
                unique=True,
                verbose_name="occasion name",
            ),
        ),
    ]
