# Generated by Django 5.0.2 on 2024-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_tag_options_alter_recipe_tags_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="recipes.tag", verbose_name="mealtimes"),
        ),
    ]
