# Generated by Django 5.0.2 on 2024-02-19 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_recipeingredient_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("name",),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="pub_date",
        ),
    ]
