# Generated by Django 5.0.2 on 2024-02-22 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_favorite_recipe_alter_favorite_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                help_text="which recipe author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribed author",
            ),
        ),
    ]
