# Generated by Django 5.0.1 on 2024-02-04 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_tag_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "mealtime",
                "verbose_name_plural": "mealtimes",
            },
        ),
    ]
