# Generated by Django 5.0.2 on 2024-02-19 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipe_options_remove_recipe_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="published on",
            ),
            preserve_default=False,
        ),
    ]
