# Generated by Django 5.0.2 on 2024-02-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_subscription_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                help_text="Who subscribes",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscriber",
            ),
        ),
    ]
