# Generated by Django 5.0.2 on 2024-02-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_subscription_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                help_text="which recipe author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_subscribed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribed author",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                help_text="Who subscribes",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscriber",
            ),
        ),
    ]
