# Generated by Django 5.0.2 on 2024-02-19 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
    ]
