# Generated by Django 5.0.2 on 2024-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("output_order",),
                "verbose_name": "mealtime",
                "verbose_name_plural": "mealtimes",
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="output_order",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="precedence order"
            ),
            preserve_default=False,
        ),
    ]
