# Generated by Django 5.0.2 on 2024-02-23 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_subscription_author_alter_subscription_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("author", models.F("user")), _negated=True),
                name="user_cannot_subscribe_to_themselves",
            ),
        ),
    ]
