# Generated by Django 5.0.2 on 2024-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_tag_options_tag_output_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="output_order",
            field=models.PositiveSmallIntegerField(verbose_name="output order"),
        ),
    ]
