# Generated by Django 5.0.2 on 2024-02-25 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_subscription_user_cannot_subscribe_to_themselves"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "mealtime", "verbose_name_plural": "mealtimes"},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="output_order",
        ),
    ]
