# Generated by Django 5.0.2 on 2024-02-25 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_alter_tag_options_remove_tag_output_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
