# Generated by Django 5.0.2 on 2024-02-20 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_recipe_unique_name_user_recipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("author",),
                "verbose_name": "favourite",
                "verbose_name_plural": "favourites",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_favorite_user_recipe",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="user",
            new_name="author",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("author", "recipe"), name="unique_favorite_user_recipe"
            ),
        ),
    ]
