# Generated by Django 5.0.2 on 2024-02-25 15:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_delete_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "default_related_name": "recipes",
                "ordering": ("-pub_date",),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_favorite_user_recipe",
        ),
        migrations.RemoveConstraint(
            model_name="recipe",
            name="unique_name_user_recipe",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Upload a <=3MB image for your recipe",
                upload_to="recipes/",
                verbose_name="recipe image",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Enter a quantity of this to use in cooking",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="recipes.ingredient",
                verbose_name="ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default=1,
                help_text="Enter a unique HEX value with the #",
                max_length=7,
                unique=True,
                validators=[recipes.validators.validate_hex_color],
                verbose_name="colour",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                help_text="Enter a unique slug",
                max_length=200,
                unique=True,
                validators=[recipes.validators.validate_slug_field],
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
