# Generated by Django 5.0.2 on 2024-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "default_related_name": "recipe_ingredient",
                "verbose_name": "recipe ingredient",
                "verbose_name_plural": "recipe ingredients",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Upload an image<=1MB for your recipe",
                upload_to="recipes/",
                verbose_name="recipe image",
            ),
        ),
    ]
