# Generated by Django 5.0.3 on 2024-03-09 11:14

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0001_squashed_0015_alter_recipeingredient_options_alter_recipe_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Upload an image<=1MB for your recipe",
                upload_to="recipes/",
                validators=[recipes.validators.validate_img_size],
                verbose_name="recipe image",
            ),
        ),
    ]
