# Generated by Django 5.0.2 on 2024-02-21 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0016_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
    ]
