# Generated by Django 5.0.2 on 2024-02-21 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0018_subscription_unique_user_author_subscribe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping",
                        to="recipes.recipe",
                        verbose_name="recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="custom user",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopping_cart",
                "verbose_name_plural": "shopping_carts",
                "ordering": ("user",),
            },
        ),
    ]
