# Generated by Django 5.0.2 on 2024-02-25 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ("email",),
                "verbose_name": "custom user",
                "verbose_name_plural": "custom users",
            },
        ),
    ]
