# Generated by Django 5.0.2 on 2024-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Enter the preferred email here",
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
