# Generated by Django 5.0.2 on 2024-02-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="which recipe author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_subscribed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subscribed author",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who subscribes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_subscriber",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique_user_author_subscribe"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("author", models.F("user")), _negated=True),
                name="user_cannot_subscribe_to_themselves",
            ),
        ),
    ]
