# Generated by Django 5.0.2 on 2024-02-08 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
